#+TITLE: Curs și Laborator 1: Instalare, configurare și familiarizare

* Instalarea limbajului
În majoritatea distribuțiilor Linux și în sistemele macOS, limbajul este deja instalat.
Conform [[https://devblogs.microsoft.com/python/python-in-the-windows-10-may-2019-update/][acestui]] articol, limbajul se instalează imediat din Store în Windows 10, începînd cu update-ul din mai 2019.

Puteți testa instalarea astfel:
- pe macOS și Linux, deschideți un terminal și scrieți ~which python~, apoi apăsați =Enter=. Dacă terminalul răspunde cu o cale precum =/usr/bin/python=, înseamnă că limbajul este instalat. Dacă primiți un mesaj precum =python: command not found=, căutați instrucțiunile corespunzătoare pentru instalarea limbajului;
- pe Windows, deschideți o consolă (Command Prompt) cu Start > Run > cmd și apăsați =Enter=, apoi scrieți =python=. Dacă primiți mesaje care se încheie cu simbolurile =>>>= pe o linie nouă, înseamnă că limbajul este instalat. Scrieți =exit()=, apăsați =Enter= și închideți consola. Dacă primiți un mesaj de eroare, urmați pașii din articolul menționat și instalați limbajul din Microsoft Store.

În urma acestui pas, ar trebui să aveți instalată ultima versiune a limbajului Python. 
Indiferent de versiunea minoră, este important ca versiunea majoră să fie 3. Testați acest
lucru introducînd în terminal sau consolă comanda =python --version=. Ar trebui să primiți
un răspuns de forma =Python 3.9.1= (important este ca prima cifră să fie 3).

* Instalarea uneltelor de lucru
În continuare, vă veți instala principalele unelte de lucru. Mai precis, un editor
text sau un IDE. Alegerea vă aparține, dar cîteva opțiuni sînt:
- vim: deja inclus în macOS și Linux, dar greu de folosit, dacă nu sînteți familiarizați cu el;
- [[https://www.gnu.org/software/emacs/][GNU Emacs]]: foarte puternic și flexibil, dar greu de folosit dacă nu aveți experiențe anterioare;
- [[https://www.jetbrains.com/pycharm/][JetBrains PyCharm]]: un IDE, care vine cu toate uneltele necesare, suficient de puternic, dar și de prietenos (un [[https://www.jetbrains.com/help/pycharm/quick-start-guide.html#c304d95f][tutorial scurt]]);
- [[https://code.visualstudio.com/][Visual Studio Code]]: un editor, cu multe plugin-uri care se pot instala pentru a-l face cît mai puternic și flexibil (exemplu: [[https://code.visualstudio.com/docs/python/python-tutorial][pachetul de Python, cu un ghid]]);

Opțional, mai puteți instala diverse plugin-uri și extensii, după preferințe, dar, de exemplu, PyCharm sau (VSCode + pachetele de Python) ar trebui să fie suficient.

Tot opțional, puteți instala [[https://docs.microsoft.com/en-us/windows/wsl/install-win10][Windows Subsystem for Linux]], pentru a avea un mediu nativ Ubuntu în Windows 10.

Veți mai avea nevoie și de Jupyter, un mediu interactiv de programare și vizualizare, pe care îl puteți instala de [[https://jupyter.org/][aici]].

Într-un sistem de tip GNU/Linux sau macOS, puteți instala Jupyter din terminal, cu comanda:
#+begin_src sh
	$ sudo pip install jupyterlab
#+end_src

Verificați apoi instalarea cu comanda
#+begin_src sh
	$ jupyter --version
	# dacă ați reușit, veți vedea:
	jupyter core     : 4.6.3
	jupyter-notebook : 6.0.3
	qtconsole        : 4.7.4
	ipython          : 7.19.10
	ipykernel        : 5.3.0
#+end_src

Pentru a folosi Jupyter, trebuie să creați un fișier (notebook) nou. Din directorul unde vreți să lucrați,
lansați kernel-ul Jupyter cu comanda:
#+begin_src sh
	# $ cd directorul/de/lucru
	$ jupyter
#+end_src

Se va deschide o fereastră de browser, cu conținutul directorului de lucru.
Creați un notebook nou din interfața grafică și scrieți într-un bloc:

#+begin_src python
	print("Merge!")
#+end_src

Apoi apăsați =Shift + Enter=. Dacă dedesubt apare mesajul =Merge!=, ați reușit.

Documentația detaliată se găsește [[https://jupyter.org/documentation][aici]].

* CHECKPOINT
Înainte de a merge mai departe, asigurați-vă că:
- aveți limbajul instalat;
- aveți un editor sau IDE instalat, împreună cu posibilele extensii esențiale (dacă este cazul);
- știți să deschideți editorul, să creați un fișier simplu, să introduceți în el, de exemplu, o linie de cod precum:
#+begin_src python
	print("Hello World!")
#+end_src
și să rulați fișierul (=Ctrl+Shift+F10= în PyCharm).
- știți să deschideți Jupyter și să creați un notebook nou.

* Exemple
Dacă ați ajuns pînă aici, vizitați [[file:exemple][folderul de exemple]], care conține atît un [[file:exemple/exemplu-jupyter.ipynb][exemplu Jupyter]], 
cît și progrămele Python.

Le puteți descărca și testa pe propriul computer sau studiați-le în browser.

* Exerciții
După familiarizarea cu limbajul și exercițiile incluse ca exemplu,
consultați centralizatorul de exerciții de [[file:../exercitii.md][aici]].
